"""
file_settings.py — Org-wide file generation settings (Admin Panel).

Stores one singleton Firestore doc at settings/file_generation with:
  - visual branding applied to every generated PDF/PPTX/HTML (colors, logo, footer)
  - written guidance appended to the agent's system prompt so the AI follows
    it whenever it generates a file in chat

Per-conversation instructions the user gives the agent directly always sit
alongside (and take priority over) these org-wide defaults — see the note
built into the system prompt in app/services/anthropic.py.
"""

from app.services.firebase import get_db

SETTINGS_COLLECTION = "settings"
SETTINGS_DOC_ID = "file_generation"

DEFAULT_FILE_SETTINGS = {
    # Visual branding — applied to the rendered file itself
    "primary_color": "#1a1a2e",
    "accent_color": "#e94560",
    "logo_url": "",
    "footer_text": "Generated by Shift AI · Telfaz11",
    # Written guidance — appended to the agent's system prompt
    "general_instructions": "",
    "pdf_instructions": "",
    "pptx_instructions": "",
    "docx_instructions": "",
    "html_instructions": "",
}


def get_file_settings() -> dict:
    """Return current org-wide file generation settings, defaults filled in for anything unset."""
    db = get_db()
    doc = db.collection(SETTINGS_COLLECTION).document(SETTINGS_DOC_ID).get()
    data = doc.to_dict() if doc.exists else {}
    return {**DEFAULT_FILE_SETTINGS, **(data or {})}


def update_file_settings(patch: dict) -> dict:
    """Merge `patch` into the stored settings (only known keys) and return the resulting settings."""
    clean_patch = {k: v for k, v in patch.items() if k in DEFAULT_FILE_SETTINGS and v is not None}
    db = get_db()
    ref = db.collection(SETTINGS_COLLECTION).document(SETTINGS_DOC_ID)
    ref.set(clean_patch, merge=True)
    return get_file_settings()
