"""
file_generator.py — Generate PDF, PPTX, and HTML files from AI chat output.

Returns bytes + a suggested filename for each format.
The router streams these back as FileResponse / Response.
"""

import io
import re
import textwrap
import urllib.request
from pathlib import Path
from datetime import datetime, timezone

# Kept in sync with app/services/file_settings.py's DEFAULT_FILE_SETTINGS —
# duplicated here (rather than imported) so file_generator has no dependency
# on Firestore/file_settings and can be used/tested standalone.
DEFAULT_BRANDING = {
    "primary_color": "#1a1a2e",
    "accent_color": "#e94560",
    "logo_url": "",
    "footer_text": "Generated by Shift AI · Telfaz11",
}

# ── Arabic support (PDF only) ─────────────────────────────────────────────────
# reportlab's built-in PDF fonts (Helvetica etc.) have no Arabic glyphs, and
# reportlab does not itself perform Arabic contextual shaping or bidi
# reordering — without this, Arabic text renders as boxes/garbled characters.
# PPTX/DOCX/HTML don't need this: they store plain Unicode text and their
# viewer (Word/PowerPoint/browser) shapes + reorders it automatically.
ARABIC_FONT_NAME = "NotoNaskhArabic"
ARABIC_FONT_PATH = Path(__file__).resolve().parent.parent / "assets" / "fonts" / "NotoNaskhArabic-Regular.ttf"
_ARABIC_RANGE_RE = re.compile(r"[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]")
_arabic_font_registered = False


def _contains_arabic(text: str) -> bool:
    return bool(_ARABIC_RANGE_RE.search(text or ""))


def _ensure_arabic_font_registered() -> bool:
    """Register the bundled Arabic font with reportlab, once. Returns False (never raises) if unavailable."""
    global _arabic_font_registered
    if _arabic_font_registered:
        return True
    try:
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont
        pdfmetrics.registerFont(TTFont(ARABIC_FONT_NAME, str(ARABIC_FONT_PATH)))
        _arabic_font_registered = True
    except Exception:
        _arabic_font_registered = False
    return _arabic_font_registered


def _prepare_pdf_text(text: str) -> str:
    """
    Reshape + bidi-reorder Arabic text for reportlab (which draws glyphs as
    given, with no shaping/reordering of its own). Non-Arabic text passes
    through unchanged. Never raises — falls back to the original text.
    """
    if not _contains_arabic(text):
        return text
    try:
        import arabic_reshaper
        from bidi.algorithm import get_display
        return get_display(arabic_reshaper.reshape(text))
    except Exception:
        return text


def _resolve_branding(branding: dict | None) -> dict:
    return {**DEFAULT_BRANDING, **(branding or {})}


def _fetch_image_bytes(url: str) -> bytes | None:
    """Best-effort fetch of a logo image. Returns None (never raises) on any failure."""
    if not url:
        return None
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "ShiftAI-FileGen/1.0"})
        with urllib.request.urlopen(req, timeout=5) as resp:
            return resp.read()
    except Exception:
        return None


# ── Helpers ───────────────────────────────────────────────────────────────────

def _safe_filename(title: str, ext: str) -> str:
    slug = re.sub(r"[^\w\s-]", "", title).strip().replace(" ", "_")[:40]
    date = datetime.now(timezone.utc).strftime("%Y%m%d")
    return f"{slug}_{date}.{ext}"


def _strip_markdown(text: str) -> str:
    """Convert basic markdown to plain text for PDF/PPTX."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)   # bold
    text = re.sub(r"\*(.+?)\*", r"\1", text)         # italic
    text = re.sub(r"`(.+?)`", r"\1", text)            # inline code
    text = re.sub(r"#{1,6}\s+", "", text)             # headings → plain
    text = re.sub(r"^\s*[-*]\s+", "• ", text, flags=re.MULTILINE)  # bullets
    return text.strip()


def sections_to_markdown(title: str, sections: list[dict]) -> str:
    """
    Convert the structured JSON the model returns (a list of sections, each
    with a heading + body text and/or bullet list) into the Markdown string
    that generate_pdf/generate_pptx/generate_html already know how to parse.

    Expected section shape (all keys optional except heading):
      {"heading": "Slide/Section Title", "body": "free text...", "bullets": ["a", "b"]}
    """
    lines: list[str] = []
    for section in sections:
        heading = (section.get("heading") or "").strip()
        if heading:
            lines.append(f"## {heading}")
        body = (section.get("body") or "").strip()
        if body:
            lines.append(body)
        for bullet in section.get("bullets") or []:
            bullet = str(bullet).strip()
            if bullet:
                lines.append(f"- {bullet}")
        lines.append("")  # blank line between sections
    return "\n".join(lines).strip()


def build_file_from_structured(
    file_type: str,
    title: str,
    sections: list[dict],
    workflow_title: str = "",
    branding: dict | None = None,
) -> tuple[bytes, str]:
    """
    file_type: "pdf" | "pptx" | "docx" | "html"
    sections: structured JSON sections (see sections_to_markdown)
    branding: optional org-wide settings (see app/services/file_settings.py) —
      primary_color, accent_color, logo_url, footer_text.
    Returns (file_bytes, filename).
    """
    content_markdown = sections_to_markdown(title, sections)
    if file_type == "pdf":
        return generate_pdf(title, content_markdown, workflow_title, branding)
    if file_type == "pptx":
        return generate_pptx(title, content_markdown, workflow_title, branding)
    if file_type == "docx":
        return generate_docx(title, content_markdown, workflow_title, branding)
    if file_type == "html":
        return generate_html(title, content_markdown, workflow_title, branding)
    raise ValueError(f"Unsupported file type: {file_type}")

def generate_pdf(title: str, content: str, workflow_title: str = "", branding: dict | None = None) -> tuple[bytes, str]:
    """
    Generate a PDF from markdown-ish text. Arabic text is automatically
    detected per line, reshaped + bidi-reordered, and rendered with a bundled
    Arabic-capable font (right-aligned) — reportlab's default fonts have no
    Arabic glyphs and don't shape/reorder Arabic on their own.
    Returns (pdf_bytes, filename).
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Image as RLImage
    from reportlab.lib.enums import TA_LEFT, TA_RIGHT

    brand = _resolve_branding(branding)
    arabic_ok = _ensure_arabic_font_registered()

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=2.5 * cm,
        rightMargin=2.5 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()
    brand_color = colors.HexColor(brand["primary_color"])
    accent_color = colors.HexColor(brand["accent_color"])

    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"], fontSize=22,
        textColor=brand_color, spaceAfter=6, alignment=TA_LEFT,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"], fontSize=10,
        textColor=colors.grey, spaceAfter=12,
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"], fontSize=11, leading=16,
        spaceAfter=8, textColor=colors.HexColor("#333333"),
    )
    heading_style = ParagraphStyle(
        "Heading", parent=styles["Heading2"], fontSize=14,
        textColor=brand_color, spaceBefore=14, spaceAfter=6, borderPad=0,
    )
    bullet_style = ParagraphStyle(
        "Bullet", parent=body_style, leftIndent=16, firstLineIndent=-16, spaceAfter=4,
    )

    # Arabic variants — same look, Arabic font + right alignment
    title_style_ar = ParagraphStyle("CustomTitleAr", parent=title_style, fontName=ARABIC_FONT_NAME, alignment=TA_RIGHT)
    subtitle_style_ar = ParagraphStyle("SubtitleAr", parent=subtitle_style, fontName=ARABIC_FONT_NAME, alignment=TA_RIGHT)
    body_style_ar = ParagraphStyle("BodyAr", parent=body_style, fontName=ARABIC_FONT_NAME, alignment=TA_RIGHT)
    heading_style_ar = ParagraphStyle("HeadingAr", parent=heading_style, fontName=ARABIC_FONT_NAME, alignment=TA_RIGHT)
    bullet_style_ar = ParagraphStyle(
        "BulletAr", parent=bullet_style, fontName=ARABIC_FONT_NAME, alignment=TA_RIGHT,
        leftIndent=0, rightIndent=16, firstLineIndent=0,
    )

    def _para(text: str, base_style, ar_style):
        if arabic_ok and _contains_arabic(text):
            return Paragraph(_prepare_pdf_text(text), ar_style)
        return Paragraph(text, base_style)

    story = []

    # Optional logo
    logo_bytes = _fetch_image_bytes(brand.get("logo_url", ""))
    if logo_bytes:
        try:
            logo_img = RLImage(io.BytesIO(logo_bytes))
            max_height = 1.4 * cm
            aspect = (logo_img.imageWidth / logo_img.imageHeight) if logo_img.imageHeight else 1
            logo_img.drawHeight = max_height
            logo_img.drawWidth = max_height * aspect
            story.append(logo_img)
            story.append(Spacer(1, 8))
        except Exception:
            pass  # corrupt/unsupported image — skip rather than fail the whole document

    # Header
    story.append(_para(title, title_style, title_style_ar))
    if workflow_title:
        story.append(_para(f"Workflow: {workflow_title}", subtitle_style, subtitle_style_ar))
    generated_at = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    story.append(Paragraph(f"Generated: {generated_at}", subtitle_style))  # always Latin/English
    story.append(HRFlowable(width="100%", thickness=2, color=accent_color, spaceAfter=16))

    # Parse content line by line
    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 6))
            continue

        if stripped.startswith("# "):
            story.append(_para(stripped[2:], heading_style, heading_style_ar))
        elif stripped.startswith("## "):
            story.append(_para(stripped[3:], heading_style, heading_style_ar))
        elif stripped.startswith("### "):
            story.append(_para(stripped[4:], heading_style, heading_style_ar))
        elif stripped.startswith(("- ", "* ", "• ")):
            text = _strip_markdown(stripped[2:])
            story.append(_para(f"• {text}", bullet_style, bullet_style_ar))
        elif re.match(r"^\d+\. ", stripped):
            text = re.sub(r"^\d+\. ", "", stripped)
            text = _strip_markdown(text)
            story.append(_para(text, bullet_style, bullet_style_ar))
        elif stripped.startswith("**") and stripped.endswith("**"):
            # Bold-only line → treat as a sub-heading
            story.append(_para(_strip_markdown(stripped), heading_style, heading_style_ar))
        else:
            story.append(_para(_strip_markdown(stripped), body_style, body_style_ar))

    footer_text = brand.get("footer_text", "")

    def _draw_footer(canvas, doc_):
        if not footer_text:
            return
        canvas.saveState()
        if arabic_ok and _contains_arabic(footer_text):
            canvas.setFont(ARABIC_FONT_NAME, 8)
            display_text = _prepare_pdf_text(footer_text)
        else:
            canvas.setFont("Helvetica", 8)
            display_text = footer_text
        canvas.setFillColor(colors.grey)
        canvas.drawCentredString(doc_.pagesize[0] / 2, 1.2 * cm, display_text)
        canvas.restoreState()

    doc.build(story, onFirstPage=_draw_footer, onLaterPages=_draw_footer)
    return buffer.getvalue(), _safe_filename(title, "pdf")


# ── PPTX ──────────────────────────────────────────────────────────────────────

def generate_pptx(title: str, content: str, workflow_title: str = "", branding: dict | None = None) -> tuple[bytes, str]:
    """
    Convert structured text into a PowerPoint presentation.
    Each markdown heading becomes a new slide.
    Returns (pptx_bytes, filename).
    """
    from pptx import Presentation
    from pptx.util import Inches, Pt, Emu
    from pptx.dml.color import RGBColor
    from pptx.enum.text import PP_ALIGN

    brand = _resolve_branding(branding)
    logo_bytes = _fetch_image_bytes(brand.get("logo_url", ""))
    footer_text = brand.get("footer_text", "")

    prs = Presentation()
    prs.slide_width = Inches(13.33)
    prs.slide_height = Inches(7.5)

    BRAND = RGBColor.from_string(brand["primary_color"].lstrip("#"))
    ACCENT = RGBColor.from_string(brand["accent_color"].lstrip("#"))
    WHITE = RGBColor(0xFF, 0xFF, 0xFF)
    LIGHT_GREY = RGBColor(0xF5, 0xF5, 0xF5)

    blank_layout = prs.slide_layouts[6]  # completely blank

    def add_slide(slide_title: str, bullets: list[str], is_title_slide: bool = False):
        slide = prs.slides.add_slide(blank_layout)

        # Background
        bg = slide.background.fill
        bg.solid()
        bg.fore_color.rgb = WHITE if not is_title_slide else BRAND

        # Accent bar (left edge)
        bar = slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(0.12), prs.slide_height)
        bar.fill.solid()
        bar.fill.fore_color.rgb = ACCENT
        bar.line.fill.background()

        # Logo (title slide only, top-right corner)
        if is_title_slide and logo_bytes:
            try:
                slide.shapes.add_picture(
                    io.BytesIO(logo_bytes), Inches(11.8), Inches(0.5), height=Inches(0.7)
                )
            except Exception:
                pass  # corrupt/unsupported image — skip rather than fail the whole deck

        # Title box
        title_top = Inches(0.5) if not is_title_slide else Inches(2.5)
        txBox = slide.shapes.add_textbox(Inches(0.35), title_top, Inches(12.5), Inches(1.2))
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = slide_title
        p.font.bold = True
        p.font.size = Pt(36) if is_title_slide else Pt(28)
        p.font.color.rgb = WHITE if is_title_slide else BRAND

        if is_title_slide and workflow_title:
            p2 = tf.add_paragraph()
            p2.text = workflow_title
            p2.font.size = Pt(16)
            p2.font.color.rgb = RGBColor(0xCC, 0xCC, 0xCC)
            p3 = tf.add_paragraph()
            p3.text = datetime.now(timezone.utc).strftime("%B %Y")
            p3.font.size = Pt(13)
            p3.font.color.rgb = RGBColor(0xAA, 0xAA, 0xAA)

        # Content bullets
        if bullets:
            content_box = slide.shapes.add_textbox(
                Inches(0.5), Inches(1.9), Inches(12.2), Inches(5.2)
            )
            ctf = content_box.text_frame
            ctf.word_wrap = True
            for i, bullet in enumerate(bullets):
                para = ctf.paragraphs[0] if i == 0 else ctf.add_paragraph()
                clean = _strip_markdown(bullet.lstrip("•-* "))
                para.text = f"• {clean}" if bullet.strip() else ""
                para.font.size = Pt(16)
                para.font.color.rgb = RGBColor(0x33, 0x33, 0x33)
                para.space_after = Pt(6)

        # Footer (content slides only)
        if not is_title_slide and footer_text:
            foot_box = slide.shapes.add_textbox(Inches(0.35), Inches(7.1), Inches(10), Inches(0.3))
            fp = foot_box.text_frame.paragraphs[0]
            fp.text = footer_text
            fp.font.size = Pt(9)
            fp.font.color.rgb = RGBColor(0xAA, 0xAA, 0xAA)

        return slide

    # Parse content into slides
    # Headings (# / ##) start a new slide; everything else becomes bullets
    slides_data: list[tuple[str, list[str]]] = []
    current_title = title
    current_bullets: list[str] = []

    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            continue
        if re.match(r"^#{1,3}\s+", stripped):
            # Save previous slide
            if current_bullets or current_title != title:
                slides_data.append((current_title, current_bullets))
            current_title = re.sub(r"^#{1,3}\s+", "", stripped)
            current_bullets = []
        else:
            current_bullets.append(stripped)

    # Flush last slide
    if current_title:
        slides_data.append((current_title, current_bullets))

    # Title slide
    add_slide(title, [], is_title_slide=True)

    # Content slides
    for slide_title, bullets in slides_data:
        # Split into max 6 bullets per slide to avoid overflow
        for chunk_start in range(0, max(1, len(bullets)), 6):
            add_slide(slide_title, bullets[chunk_start:chunk_start + 6])

    buffer = io.BytesIO()
    prs.save(buffer)
    return buffer.getvalue(), _safe_filename(title, "pptx")


# ── DOCX ──────────────────────────────────────────────────────────────────────

def _add_docx_heading(doc, text: str, color, size: int = 14):
    from docx.shared import Pt
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.bold = True
    run.font.size = Pt(size)
    run.font.color.rgb = color
    p.paragraph_format.space_before = Pt(10)
    p.paragraph_format.space_after = Pt(4)


def generate_docx(title: str, content: str, workflow_title: str = "", branding: dict | None = None) -> tuple[bytes, str]:
    """
    Generate a Word (.docx) document from markdown-ish text.
    Parses the same line conventions as generate_pdf (# / ## / ### headings,
    - / * / • bullets, 1. numbered lists, **bold** sub-headings, plain body text).
    Returns (docx_bytes, filename).
    """
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    brand = _resolve_branding(branding)
    brand_rgb = RGBColor.from_string(brand["primary_color"].lstrip("#"))

    doc = Document()
    doc.styles["Normal"].font.name = "Calibri"
    doc.styles["Normal"].font.size = Pt(11)

    # Optional logo
    logo_bytes = _fetch_image_bytes(brand.get("logo_url", ""))
    if logo_bytes:
        try:
            doc.add_picture(io.BytesIO(logo_bytes), height=Inches(0.5))
        except Exception:
            pass  # corrupt/unsupported image — skip rather than fail the whole document

    # Title
    title_para = doc.add_paragraph()
    title_run = title_para.add_run(title)
    title_run.font.size = Pt(24)
    title_run.font.bold = True
    title_run.font.color.rgb = brand_rgb

    # Subtitle (workflow + generated date)
    generated_at = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    subtitle_text = (
        f"Workflow: {workflow_title}   |   Generated: {generated_at}"
        if workflow_title else f"Generated: {generated_at}"
    )
    subtitle_para = doc.add_paragraph()
    subtitle_run = subtitle_para.add_run(subtitle_text)
    subtitle_run.font.size = Pt(9)
    subtitle_run.font.color.rgb = RGBColor(0x77, 0x77, 0x77)
    subtitle_para.paragraph_format.space_after = Pt(14)

    # Parse content line by line
    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            doc.add_paragraph()
            continue

        if stripped.startswith("# "):
            _add_docx_heading(doc, stripped[2:], brand_rgb, size=16)
        elif stripped.startswith("## "):
            _add_docx_heading(doc, stripped[3:], brand_rgb, size=14)
        elif stripped.startswith("### "):
            _add_docx_heading(doc, stripped[4:], brand_rgb, size=12)
        elif stripped.startswith(("- ", "* ", "• ")):
            text = _strip_markdown(stripped[2:])
            doc.add_paragraph(text, style="List Bullet")
        elif re.match(r"^\d+\. ", stripped):
            text = re.sub(r"^\d+\. ", "", stripped)
            text = _strip_markdown(text)
            doc.add_paragraph(text, style="List Number")
        elif stripped.startswith("**") and stripped.endswith("**"):
            _add_docx_heading(doc, _strip_markdown(stripped), brand_rgb, size=12)
        else:
            p = doc.add_paragraph()
            p.add_run(_strip_markdown(stripped)).font.size = Pt(11)

    # Footer
    footer_text = brand.get("footer_text", "")
    if footer_text:
        footer_para = doc.sections[0].footer.paragraphs[0]
        footer_para.text = footer_text
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in footer_para.runs:
            run.font.size = Pt(8)
            run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue(), _safe_filename(title, "docx")


# ── HTML ──────────────────────────────────────────────────────────────────────

def generate_html(title: str, content: str, workflow_title: str = "", branding: dict | None = None) -> tuple[bytes, str]:
    """
    Convert markdown content to a styled standalone HTML file.
    Returns (html_bytes, filename).
    """
    brand = _resolve_branding(branding)
    # Very lightweight markdown → HTML conversion (no external deps)
    lines = content.split("\n")
    html_lines = []
    in_ul = False
    in_ol = False

    def close_lists():
        nonlocal in_ul, in_ol
        if in_ul:
            html_lines.append("</ul>")
            in_ul = False
        if in_ol:
            html_lines.append("</ol>")
            in_ol = False

    def inline_md(text: str) -> str:
        text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
        text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
        text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
        return text

    for line in lines:
        stripped = line.strip()

        if not stripped:
            close_lists()
            html_lines.append("<br>")
            continue

        if stripped.startswith("# "):
            close_lists()
            html_lines.append(f"<h1>{inline_md(stripped[2:])}</h1>")
        elif stripped.startswith("## "):
            close_lists()
            html_lines.append(f"<h2>{inline_md(stripped[3:])}</h2>")
        elif stripped.startswith("### "):
            close_lists()
            html_lines.append(f"<h3>{inline_md(stripped[4:])}</h3>")
        elif re.match(r"^\d+\. ", stripped):
            if not in_ol:
                close_lists()
                html_lines.append("<ol>")
                in_ol = True
            text = re.sub(r"^\d+\. ", "", stripped)
            html_lines.append(f"<li>{inline_md(text)}</li>")
        elif stripped.startswith(("- ", "* ", "• ")):
            if not in_ul:
                close_lists()
                html_lines.append("<ul>")
                in_ul = True
            html_lines.append(f"<li>{inline_md(stripped[2:])}</li>")
        else:
            close_lists()
            html_lines.append(f"<p>{inline_md(stripped)}</p>")

    close_lists()
    body = "\n".join(html_lines)

    import html as html_lib

    generated_at = datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")
    footer_text = html_lib.escape(brand.get("footer_text", ""))
    logo_url = brand.get("logo_url", "")
    logo_html = f'<img src="{html_lib.escape(logo_url)}" alt="Logo" class="logo">' if logo_url else ""

    html = textwrap.dedent(f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>
    :root {{
      --brand: {brand["primary_color"]};
      --accent: {brand["accent_color"]};
      --text: #333;
      --muted: #777;
      --bg: #fff;
      --surface: #f8f8fc;
      --border: #e5e5e5;
    }}
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      color: var(--text);
      background: var(--bg);
      line-height: 1.7;
      max-width: 820px;
      margin: 0 auto;
      padding: 2rem 1.5rem 4rem;
    }}
    header {{
      border-bottom: 3px solid var(--accent);
      padding-bottom: 1.5rem;
      margin-bottom: 2rem;
    }}
    header .logo {{
      max-height: 40px;
      margin-bottom: 0.75rem;
    }}
    header h1 {{
      font-size: 2rem;
      color: var(--brand);
      margin-bottom: 0.25rem;
    }}
    header .meta {{
      font-size: 0.85rem;
      color: var(--muted);
    }}
    h1, h2, h3 {{ color: var(--brand); margin: 1.8rem 0 0.6rem; }}
    h1 {{ font-size: 1.75rem; }}
    h2 {{ font-size: 1.35rem; border-bottom: 1px solid var(--border); padding-bottom: 0.3rem; }}
    h3 {{ font-size: 1.1rem; }}
    p {{ margin: 0.7rem 0; }}
    ul, ol {{ margin: 0.7rem 0 0.7rem 1.5rem; }}
    li {{ margin: 0.3rem 0; }}
    code {{
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 4px;
      padding: 0.1em 0.4em;
      font-size: 0.9em;
      font-family: 'SF Mono', 'Fira Code', monospace;
    }}
    strong {{ color: var(--brand); }}
    footer {{
      margin-top: 3rem;
      padding-top: 1rem;
      border-top: 1px solid var(--border);
      font-size: 0.8rem;
      color: var(--muted);
    }}
    @media print {{
      body {{ max-width: none; padding: 1rem; }}
    }}
  </style>
</head>
<body>
  <header>
    {logo_html}
    <h1>{title}</h1>
    <div class="meta">
      {"<span>Workflow: " + workflow_title + " &nbsp;|&nbsp; </span>" if workflow_title else ""}
      <span>Generated: {generated_at}</span>
    </div>
  </header>
  <main>
{body}
  </main>
  <footer>{footer_text}</footer>
</body>
</html>""")

    return html.encode("utf-8"), _safe_filename(title, "html")
